/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import classesDB.DAOPhotoFlow;
import classesDB.DBGrupo;
import classesDB.DBTipo_Agendamento;
import classesDB.DBUsuario;
import componentes.TextDocument;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Marlei M.S.B.
 */
public class TelaDadosMestre extends javax.swing.JInternalFrame {
    private Connection con; 
    private DAOPhotoFlow daoAtmus; 
    private int cod_tpAgendamento;
    private int cod_grupo;
    /**
     * Creates new form TelaCliente
     */
    public TelaDadosMestre() {
        initComponents();
    }

    /**
     * Creates new form TelaCliente
     * @param con 
     */
    public TelaDadosMestre(Connection con) {
        initComponents();
        this.con = con; 
    }    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        descricao_grupo_jtf = new javax.swing.JTextField();
        cod_grupo_jftf = new javax.swing.JFormattedTextField();
        cor_R_grupo_jftf = new javax.swing.JFormattedTextField();
        cor_G_grupo_jftf = new javax.swing.JFormattedTextField();
        cor_B_grupo_jftf = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        salvar_grupo_bt = new javax.swing.JButton();
        excluir_grupo_bt = new javax.swing.JButton();
        cancelar_grupo_bt = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_grupos_jtb = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cod_usuario_jtf = new javax.swing.JTextField();
        nome_usuario_jtf = new javax.swing.JTextField();
        senha_usuario_jpf = new javax.swing.JPasswordField();
        tipo_usuario_jcb = new javax.swing.JComboBox<>();
        revogado_usuario_rb = new javax.swing.JRadioButton();
        ativo_usuario_rb = new javax.swing.JRadioButton();
        senhaBloqueada_usuario_rb = new javax.swing.JRadioButton();
        senhaDesbloqueada_rb = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        data_acesso_usuario_jtf = new javax.swing.JTextField();
        data_atualizacao_usuario_jtf = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        salvar_usuario_bt = new javax.swing.JButton();
        excluir_usuario_bt = new javax.swing.JButton();
        cancelar_usuario_bt = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_usuarios_jtb = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        descricao_tpAgendamento_jtf = new javax.swing.JTextField();
        tempo_medio_tpAgendamento_jftf = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        hora_inicio_sug_jftf = new javax.swing.JFormattedTextField();
        hora_fim_sug_jftf = new javax.swing.JFormattedTextField();
        justificativa_tpAgendamento_jtf = new javax.swing.JTextField();
        grupo_tpAgendamento = new javax.swing.JTextField();
        buscarGrupo_tpAgendamento_bt = new javax.swing.JButton();
        margem_segurança_jftf = new javax.swing.JFormattedTextField();
        jPanel13 = new javax.swing.JPanel();
        salvar_tpAgendamento = new javax.swing.JButton();
        excluir_tpAgendamento = new javax.swing.JButton();
        cancelar_tpAgendamento = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_tpAgendamento_JT = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Dados Mestre");
        setPreferredSize(new java.awt.Dimension(744, 546));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Cod");

        jLabel2.setText("Descrição");

        jLabel3.setText("Cor (RGB)");

        descricao_grupo_jtf.setDocument(new TextDocument(50));
        descricao_grupo_jtf.setToolTipText("Nome do Grupo");

        cod_grupo_jftf.setEditable(false);
        cod_grupo_jftf.setDocument(new TextDocument(7));
        cod_grupo_jftf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        cor_R_grupo_jftf.setDocument(new TextDocument(3));
        cor_R_grupo_jftf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cor_R_grupo_jftf.setToolTipText("Cor canal R {0 - 255}");

        cor_G_grupo_jftf.setDocument(new TextDocument(3));
        cor_G_grupo_jftf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cor_G_grupo_jftf.setToolTipText("Cor canal G {0 - 255}");

        cor_B_grupo_jftf.setDocument(new TextDocument(3));
        cor_B_grupo_jftf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cor_B_grupo_jftf.setToolTipText("Cor canal B {0 - 255}");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descricao_grupo_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cod_grupo_jftf, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cor_R_grupo_jftf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cor_G_grupo_jftf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cor_B_grupo_jftf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cod_grupo_jftf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(descricao_grupo_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cor_R_grupo_jftf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cor_G_grupo_jftf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cor_B_grupo_jftf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        salvar_grupo_bt.setText("Salvar");
        salvar_grupo_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_grupo_btActionPerformed(evt);
            }
        });

        excluir_grupo_bt.setText("Excluir");
        excluir_grupo_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_grupo_btActionPerformed(evt);
            }
        });

        cancelar_grupo_bt.setText("Cancelar");
        cancelar_grupo_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_grupo_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(salvar_grupo_bt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excluir_grupo_bt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelar_grupo_bt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar_grupo_bt)
                    .addComponent(excluir_grupo_bt)
                    .addComponent(cancelar_grupo_bt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lista_grupos_jtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod", "Descrição", "Cor R", "Cor G", "Cor B"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lista_grupos_jtb.setToolTipText("Lista de grupos");
        lista_grupos_jtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_grupos_jtbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lista_grupos_jtb);
        if (lista_grupos_jtb.getColumnModel().getColumnCount() > 0) {
            lista_grupos_jtb.getColumnModel().getColumn(0).setPreferredWidth(13);
            lista_grupos_jtb.getColumnModel().getColumn(2).setPreferredWidth(7);
            lista_grupos_jtb.getColumnModel().getColumn(3).setPreferredWidth(7);
            lista_grupos_jtb.getColumnModel().getColumn(4).setPreferredWidth(7);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Grupos", jPanel4);

        jLabel4.setText("User ID");

        jLabel5.setText("Nome");

        jLabel6.setText("Senha");

        jLabel7.setText("Data Atualização");

        jLabel8.setText("Tipo");

        cod_usuario_jtf.setDocument(new TextDocument(8));
        cod_usuario_jtf.setToolTipText("Identificador único do usuário {Máximo 8 caracteres}");

        nome_usuario_jtf.setDocument(new TextDocument(35));
        nome_usuario_jtf.setToolTipText("Nome completo do usuário");

        senha_usuario_jpf.setDocument(new TextDocument(15));
        senha_usuario_jpf.setToolTipText("Senha para acesso ao sistema {Máximo 15 caracteres}");

        tipo_usuario_jcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "adm", "Fotógrafo", "Vendedor" }));

        buttonGroup1.add(revogado_usuario_rb);
        revogado_usuario_rb.setText("Usuário Revogado");

        buttonGroup1.add(ativo_usuario_rb);
        ativo_usuario_rb.setText("Usuário Ativo");

        buttonGroup2.add(senhaBloqueada_usuario_rb);
        senhaBloqueada_usuario_rb.setText("Senha Bloqueada");

        buttonGroup2.add(senhaDesbloqueada_rb);
        senhaDesbloqueada_rb.setText("Senha Desbloqueada");

        jLabel15.setText("Data Último Acesso");

        data_acesso_usuario_jtf.setEditable(false);
        data_acesso_usuario_jtf.setToolTipText("Data do último acesso {automático}");

        data_atualizacao_usuario_jtf.setEditable(false);
        data_atualizacao_usuario_jtf.setToolTipText("Data da última atualização de Senha {automático}");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipo_usuario_jcb, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cod_usuario_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome_usuario_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(revogado_usuario_rb)
                            .addComponent(ativo_usuario_rb))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senhaBloqueada_usuario_rb)
                            .addComponent(senhaDesbloqueada_rb)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(data_atualizacao_usuario_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(data_acesso_usuario_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(senha_usuario_jpf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cod_usuario_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nome_usuario_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(senha_usuario_jpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15)
                    .addComponent(data_acesso_usuario_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_atualizacao_usuario_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tipo_usuario_jcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(revogado_usuario_rb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ativo_usuario_rb))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(senhaBloqueada_usuario_rb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(senhaDesbloqueada_rb)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        salvar_usuario_bt.setText("Salvar");
        salvar_usuario_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_usuario_btActionPerformed(evt);
            }
        });

        excluir_usuario_bt.setText("Excluir");
        excluir_usuario_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_usuario_btActionPerformed(evt);
            }
        });

        cancelar_usuario_bt.setText("Cancelar");
        cancelar_usuario_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_usuario_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(salvar_usuario_bt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excluir_usuario_bt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelar_usuario_bt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar_usuario_bt)
                    .addComponent(excluir_usuario_bt)
                    .addComponent(cancelar_usuario_bt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lista_usuarios_jtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Nome", "Permissões", "Atualização Senha", "Status Senha", "Último Acesso ", "Status User"
            }
        ));
        lista_usuarios_jtb.setToolTipText("Lista de Usuários cadastrados");
        lista_usuarios_jtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_usuarios_jtbMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lista_usuarios_jtb);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuários", jPanel7);

        jPanel11.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel11ComponentShown(evt);
            }
        });

        jLabel10.setText("Descrição");

        jLabel11.setText("Tempo Médio");

        jLabel12.setText("Margem de Segurança");

        jLabel13.setText("Justificativa");

        descricao_tpAgendamento_jtf.setDocument(new TextDocument(25));
        descricao_tpAgendamento_jtf.setToolTipText("Tipo de agendamento, reflete uma tarefa que será agendada");

        tempo_medio_tpAgendamento_jftf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));
        tempo_medio_tpAgendamento_jftf.setToolTipText("Tempo necessário para executar esse tipo de tarefa {HH:MM:SS}");

        jLabel9.setText("Hora Inicio Sugerida");

        jLabel14.setText("Hora Fim Sugerida");

        hora_inicio_sug_jftf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));
        hora_inicio_sug_jftf.setToolTipText("Inicio do melhor período do dia para executar esse tipo de tarefa {HH:MM:SS}");

        hora_fim_sug_jftf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));
        hora_fim_sug_jftf.setToolTipText("Fim do melhor período do dia para executar esse tipo de tarefa {HH:MM:SS}");

        justificativa_tpAgendamento_jtf.setDocument(new TextDocument(50));
        justificativa_tpAgendamento_jtf.setToolTipText("Motivo pelo qual o período indicado é o melhor para esse tipo de tarefa");

        grupo_tpAgendamento.setToolTipText("Grupo ao qual o tipo de agendamento pertence");

        buscarGrupo_tpAgendamento_bt.setText("Buscar Grupo");

        margem_segurança_jftf.setDocument(new TextDocument(3));
        margem_segurança_jftf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        margem_segurança_jftf.setToolTipText("Margem de seguraça em % ");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(buscarGrupo_tpAgendamento_bt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hora_inicio_sug_jftf, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(tempo_medio_tpAgendamento_jftf, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hora_fim_sug_jftf, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(margem_segurança_jftf)))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(descricao_tpAgendamento_jtf)
                        .addComponent(justificativa_tpAgendamento_jtf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                        .addComponent(grupo_tpAgendamento, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(descricao_tpAgendamento_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tempo_medio_tpAgendamento_jftf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(margem_segurança_jftf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(hora_inicio_sug_jftf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora_fim_sug_jftf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(justificativa_tpAgendamento_jtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grupo_tpAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarGrupo_tpAgendamento_bt))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        salvar_tpAgendamento.setText("Salvar");
        salvar_tpAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_tpAgendamentoActionPerformed(evt);
            }
        });

        excluir_tpAgendamento.setText("Excluir");
        excluir_tpAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_tpAgendamentoActionPerformed(evt);
            }
        });

        cancelar_tpAgendamento.setText("Cancelar");
        cancelar_tpAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_tpAgendamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(salvar_tpAgendamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excluir_tpAgendamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelar_tpAgendamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar_tpAgendamento)
                    .addComponent(excluir_tpAgendamento)
                    .addComponent(cancelar_tpAgendamento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lista_tpAgendamento_JT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod", "Descricao", "Tempo Médio", "Grupo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lista_tpAgendamento_JT.setToolTipText("Lista de tipos de agendamentos");
        lista_tpAgendamento_JT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_tpAgendamento_JTMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lista_tpAgendamento_JT);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tipo de Agendamento", jPanel11);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Fornecedores", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvar_grupo_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_grupo_btActionPerformed
        if ( (!descricao_grupo_jtf.getText().trim().equals("")) 
          && (!cor_R_grupo_jftf.getText().trim().equals(""))
          && (!cor_G_grupo_jftf.getText().trim().equals(""))
          && (!cor_B_grupo_jftf.getText().trim().equals(""))){
            int corR = Integer.parseInt(cor_R_grupo_jftf.getText());
            int corG = Integer.parseInt(cor_G_grupo_jftf.getText());
            int corB = Integer.parseInt(cor_B_grupo_jftf.getText()); 
            if(corR > 255){
                corR = 255;
            }
            if(corG > 255){
                corG = 255;
            }
            if(corB > 255){
                corB = 255; 
            }
            int cod = 0;
            if(!cod_grupo_jftf.getText().trim().equals("")){
                cod = Integer.parseInt(cod_grupo_jftf.getText());
            }
            
            DBGrupo grupo = new DBGrupo(cod, descricao_grupo_jtf.getText().trim(), corR, corG, corB);
            try {
                if (cod == 0) {
                    DAOPhotoFlow.insertGrupo(con, grupo);
                }else{
                    DAOPhotoFlow.updateGrupo(con, grupo);
                }
                                  
               //carrega lista atualizada
               load_lista_grupos_jT();
               limparTelaGrupo();
            } catch (SQLException ex) {
                Logger.getLogger(TelaConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            if(descricao_grupo_jtf.getText().trim().equals("")){
                descricao_grupo_jtf.requestFocus();
            }else{
                if (cor_R_grupo_jftf.getText().trim().equals("")) {
                    cor_R_grupo_jftf.requestFocus();
                }else{
                    if (cor_G_grupo_jftf.getText().trim().equals("")) {
                        cor_G_grupo_jftf.requestFocus();
                    }else{
                        if(cor_B_grupo_jftf.getText().trim().equals("")){
                            cor_B_grupo_jftf.requestFocus();
                        }
                    }
                }
            }   
        } 
    }//GEN-LAST:event_salvar_grupo_btActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        load_lista_grupos_jT();
        load_lista_usuario_jtb();
        load_lista_tpAgendamento_jT();
    }//GEN-LAST:event_formComponentShown

    private void lista_grupos_jtbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_grupos_jtbMouseClicked
        int lin = lista_grupos_jtb.getSelectedRow();
        int cod = (int)lista_grupos_jtb.getValueAt(lin, 0);
        String desc = lista_grupos_jtb.getValueAt(lin, 1).toString();
        int corR = (int)lista_grupos_jtb.getValueAt(lin, 2);
        int corG = (int)lista_grupos_jtb.getValueAt(lin, 3);
        int corB = (int)lista_grupos_jtb.getValueAt(lin, 4);
        DBGrupo grupo = new  DBGrupo(cod, desc, corR, corG, corB);
        load_grupo(grupo);
    }//GEN-LAST:event_lista_grupos_jtbMouseClicked

    private void excluir_grupo_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_grupo_btActionPerformed
        if(!cod_grupo_jftf.getText().trim().equals("")){
            int conf = Mensagem.confirmarExclusao();
            if(conf == 0){ //se confirma excluão            
                DBGrupo grupo = new DBGrupo(Integer.parseInt(cod_grupo_jftf.getText()), "", 0, 0, 0);
                try {
                    DAOPhotoFlow.deleteGrupo(con, grupo);
                    limparTelaGrupo();
                    load_lista_grupos_jT();
                } catch (SQLException ex) {
                    Logger.getLogger(TelaDadosMestre.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_excluir_grupo_btActionPerformed

    private void cancelar_grupo_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_grupo_btActionPerformed
        limparTelaGrupo();
    }//GEN-LAST:event_cancelar_grupo_btActionPerformed

    private void cancelar_usuario_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_usuario_btActionPerformed
        limparTelaUser();
    }//GEN-LAST:event_cancelar_usuario_btActionPerformed

    private void excluir_usuario_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_usuario_btActionPerformed
        if(!cod_usuario_jtf.getText().trim().equals("")){
            int conf = Mensagem.confirmarExclusao();
            if(conf == 0){ //se confirma excluão            
                DBUsuario usuario = new DBUsuario(cod_usuario_jtf.getText(), "", "", "", "", "", false, false);
                try {
                    DAOPhotoFlow.deleteUsuario(con, usuario);
                    limparTelaUser();
                    load_lista_usuario_jtb();
                } catch (SQLException ex) {
                    Logger.getLogger(TelaDadosMestre.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_excluir_usuario_btActionPerformed

    private void lista_usuarios_jtbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_usuarios_jtbMouseClicked
        int lin = lista_usuarios_jtb.getSelectedRow();
        String userID = lista_usuarios_jtb.getValueAt(lin, 0).toString();
        String nome = lista_usuarios_jtb.getValueAt(lin, 1).toString();
        String tipo = lista_usuarios_jtb.getValueAt(lin, 2).toString();
        String dataAtu = lista_usuarios_jtb.getValueAt(lin, 3).toString();
        boolean statusSenha = (boolean) lista_usuarios_jtb.getValueAt(lin, 4); 
        String dataAcess = lista_usuarios_jtb.getValueAt(lin, 5).toString();
        boolean statusUser = (boolean) lista_usuarios_jtb.getValueAt(lin, 6); 
                  
        DBUsuario usuario = new DBUsuario(userID, nome, "*********", dataAtu, tipo, dataAcess, statusUser, statusSenha);

        load_usuario(usuario);
    }//GEN-LAST:event_lista_usuarios_jtbMouseClicked

    private void salvar_usuario_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_usuario_btActionPerformed
        if ( (!cod_usuario_jtf.getText().trim().equals("")) 
          && (!nome_usuario_jtf.getText().trim().equals(""))
          && (!senha_usuario_jpf.getText().trim().equals(""))){
           
            String senha = new String (senha_usuario_jpf.getPassword());  
            
            DBUsuario usuario = new DBUsuario(cod_usuario_jtf.getText(), nome_usuario_jtf.getText(), 
                                              senha, data_atualizacao_usuario_jtf.getText(), 
                                              tipo_usuario_jcb.getSelectedItem().toString(), 
                                              data_acesso_usuario_jtf.getText(), 
                                              ativo_usuario_rb.isSelected(), senhaDesbloqueada_rb.isSelected());
            
            
            try {
                DBUsuario usert = DAOPhotoFlow.selectUsuario(con, cod_usuario_jtf.getText().trim());
                if (usert == null) {
                    DAOPhotoFlow.insertUsuario(con, usuario);
                }else{
                    DAOPhotoFlow.updateUsuario(con, usuario);
                }
                
                                  
               //carrega lista atualizada
               load_lista_usuario_jtb();
               limparTelaUser();
            } catch (SQLException ex) {
                Logger.getLogger(TelaConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            if(cod_usuario_jtf.getText().trim().equals("")){
                cod_usuario_jtf.requestFocus();
            }else{
                if (nome_usuario_jtf.getText().trim().equals("")) {
                    nome_usuario_jtf.requestFocus();
                }else{
                    if (senha_usuario_jpf.getText().trim().equals("")) {
                        senha_usuario_jpf.requestFocus();
                    }
                }
            }   
        } 
    }//GEN-LAST:event_salvar_usuario_btActionPerformed

    private void cancelar_tpAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_tpAgendamentoActionPerformed
        limparTelaTpAgendamento();
    }//GEN-LAST:event_cancelar_tpAgendamentoActionPerformed

    private void excluir_tpAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_tpAgendamentoActionPerformed
        if(getCod_tpAgendamento() != 0){
            int conf = Mensagem.confirmarExclusao();
            if(conf == 0){ //se confirma excluão
                try {
                    DAOPhotoFlow.deleteTipoAgendamento(con, getCod_tpAgendamento());
                    limparTelaTpAgendamento();
                    load_lista_tpAgendamento_jT();
                } catch (SQLException ex) {
                    Logger.getLogger(TelaDadosMestre.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_excluir_tpAgendamentoActionPerformed

    private void salvar_tpAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_tpAgendamentoActionPerformed
        if ( (!descricao_tpAgendamento_jtf.getText().trim().equals("")) 
          && (!tempo_medio_tpAgendamento_jftf.getText().trim().equals(""))
          && (!margem_segurança_jftf.getText().trim().equals(""))
          && (!hora_inicio_sug_jftf.getText().trim().equals(""))
          && (!hora_fim_sug_jftf.getText().trim().equals(""))
          && (!justificativa_tpAgendamento_jtf.getText().trim().equals(""))
          && (!grupo_tpAgendamento.getText().trim().equals(""))){
            
            DBTipo_Agendamento tpAgendamento = new DBTipo_Agendamento(getCod_tpAgendamento(),
                                              descricao_tpAgendamento_jtf.getText(), tempo_medio_tpAgendamento_jftf.getText(),
                                              Double.parseDouble(margem_segurança_jftf.getText()), 
                                              hora_inicio_sug_jftf.getText(), hora_fim_sug_jftf.getText(),
                                              justificativa_tpAgendamento_jtf.getText(), getCod_grupo(), descricao_grupo_jtf.getText());
            
            
            try {
                if (getCod_tpAgendamento() == 0) {
                    DAOPhotoFlow.insertTipoAgendamento(con, tpAgendamento);
                }else{
                    DAOPhotoFlow.updateTipoAgendamento(con, tpAgendamento);
                }
                
                                  
               //carrega lista atualizada
               load_lista_tpAgendamento_jT();
               limparTelaTpAgendamento();
            } catch (SQLException ex) {
                Logger.getLogger(TelaConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            if(descricao_tpAgendamento_jtf.getText().trim().equals("")){
                descricao_tpAgendamento_jtf.requestFocus();
            }else{
                if (tempo_medio_tpAgendamento_jftf.getText().trim().equals("")) {
                    tempo_medio_tpAgendamento_jftf.requestFocus();
                }else{
                    if (margem_segurança_jftf.getText().trim().equals("")) {
                        margem_segurança_jftf.requestFocus();
                    }else{
                        if (hora_inicio_sug_jftf.getText().trim().equals("")) {
                            hora_inicio_sug_jftf.requestFocus();
                        }else{
                            if (hora_fim_sug_jftf.getText().trim().equals("")) {
                                hora_fim_sug_jftf.requestFocus();
                            }else{
                                if (justificativa_tpAgendamento_jtf.getText().trim().equals("")) {
                                    justificativa_tpAgendamento_jtf.requestFocus();
                                }else{
                                    if (grupo_tpAgendamento.getText().trim().equals("")) {
                                        grupo_tpAgendamento.requestFocus();
                                    }
                                }
                            }
                        }
                    }
                }
            }   
        } 
    }//GEN-LAST:event_salvar_tpAgendamentoActionPerformed

    private void jPanel11ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel11ComponentShown
        if (!cod_grupo_jftf.getText().trim().equals("")){
            setCod_grupo(Integer.parseInt(cod_grupo_jftf.getText()));
            grupo_tpAgendamento.setText(descricao_grupo_jtf.getText());
        }
    }//GEN-LAST:event_jPanel11ComponentShown

    private void lista_tpAgendamento_JTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_tpAgendamento_JTMouseClicked
        int lin = lista_tpAgendamento_JT.getSelectedRow();
        int cod = (int)lista_tpAgendamento_JT.getValueAt(lin, 0);
        try { 
            DBTipo_Agendamento tpAgendamento = DAOPhotoFlow.selectTipoAgendamento(con, cod);
            load_tpAgendamento(tpAgendamento);
        } catch (SQLException ex) {
            Logger.getLogger(TelaDadosMestre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lista_tpAgendamento_JTMouseClicked

    /**
     * Carrega lista atualizada de status no componente lista_status_jl
     */
    private void load_lista_grupos_jT(){
        try {
            List lista_grupos = DAOPhotoFlow.selectAllGrupo(con);
            
            DefaultTableModel tableModel = (DefaultTableModel)lista_grupos_jtb.getModel();
            tableModel.setNumRows(0);
            for (Object grupos : lista_grupos) {
                DBGrupo grupo  = (DBGrupo) grupos;
                tableModel.addRow(new Object[]{grupo.getCod(), grupo.getDescricao(), grupo.getCorR(), grupo.getCorG(), grupo.getCorB()});
            }                    
            lista_grupos_jtb.setModel(tableModel);
        } catch (SQLException ex) {
            Logger.getLogger(TelaConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    

    /**
     * Carrega lista atualizada de status no componente lista_usuario_jbt
     */
    private void load_lista_usuario_jtb(){
        try {
            List lista_usuarios = DAOPhotoFlow.selectAllUsuario(con);
            
            DefaultTableModel tableModel = (DefaultTableModel)lista_usuarios_jtb.getModel();
            tableModel.setNumRows(0);
            for (Object usuario : lista_usuarios) {
                DBUsuario user  = (DBUsuario) usuario;
                tableModel.addRow(new Object[]{user.getUser_id(), user.getNome(), user.getTipo(), user.getData_atualizacao(), user.isSenha_expirada(), user.getData_ult_acesso(), user.isUsuario_revogado()});
            }                    
            lista_usuarios_jtb.setModel(tableModel);
        } catch (SQLException ex) {
            Logger.getLogger(TelaConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }     
 
    /**
     * Carrega lista atualizada de status no componente lista_tpAgendamento_jT
     */
    private void load_lista_tpAgendamento_jT(){
        try {
            List lista_tpAgendamentos = DAOPhotoFlow.selectAllTipoAgendamento(con);
            
            DefaultTableModel tableModel = (DefaultTableModel)lista_tpAgendamento_JT.getModel();
            tableModel.setNumRows(0);
            for (Object tpAgendamento : lista_tpAgendamentos) {
                DBTipo_Agendamento tpAg = (DBTipo_Agendamento) tpAgendamento;  
                tableModel.addRow(new Object[]{tpAg.getCod(), tpAg.getDescricao(), tpAg.getTempo_medio(), tpAg.getDescricao_grupo()});
            }                    
            lista_tpAgendamento_JT.setModel(tableModel);
        } catch (SQLException ex) {
            Logger.getLogger(TelaConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }     
    
    /**
     * Carrega campos superiores 
     */
    private void load_grupo(DBGrupo grupo){
        cod_grupo_jftf.setText(Integer.toString(grupo.getCod()));
        descricao_grupo_jtf.setText(grupo.getDescricao());
        cor_R_grupo_jftf.setValue(grupo.getCorR());
        cor_G_grupo_jftf.setValue(grupo.getCorG());
        cor_B_grupo_jftf.setValue(grupo.getCorB());
    }

    private void load_usuario(DBUsuario user){
        cod_usuario_jtf.setText(user.getUser_id());
        nome_usuario_jtf.setText(user.getNome());
        senha_usuario_jpf.setText(user.getSenha());
        data_atualizacao_usuario_jtf.setText(user.getData_atualizacao());
        data_acesso_usuario_jtf.setText(user.getData_ult_acesso());
        ativo_usuario_rb.setSelected(user.isUsuario_revogado());
        revogado_usuario_rb.setSelected(!user.isUsuario_revogado());
        senhaDesbloqueada_rb.setSelected(user.isSenha_expirada());
        senhaBloqueada_usuario_rb.setSelected(!user.isSenha_expirada());                
        tipo_usuario_jcb.setSelectedItem(user.getTipo());
    }
    
    private void load_tpAgendamento(DBTipo_Agendamento tpAgendamento){
        descricao_tpAgendamento_jtf.setText(tpAgendamento.getDescricao());
        tempo_medio_tpAgendamento_jftf.setText(tpAgendamento.getTempo_medio());
        margem_segurança_jftf.setText(String.valueOf(tpAgendamento.getMargem_seguranca()));
        hora_inicio_sug_jftf.setText(tpAgendamento.getHora_ini_suger());
        hora_fim_sug_jftf.setText(tpAgendamento.getHora_fim_suger());
        justificativa_tpAgendamento_jtf.setText(tpAgendamento.getJustific_period());
        grupo_tpAgendamento.setText(tpAgendamento.getDescricao_grupo());
        setCod_tpAgendamento(tpAgendamento.getCod());
        setCod_grupo(tpAgendamento.getCod_grupo());
    }
    
    private void limparTelaGrupo(){
        cod_grupo_jftf.setText("");
        descricao_grupo_jtf.setText("");
        cor_B_grupo_jftf.setText("");
        cor_G_grupo_jftf.setText("");
        cor_R_grupo_jftf.setText("");
    }
  
    private void limparTelaUser(){
        cod_usuario_jtf.setText("");
        nome_usuario_jtf.setText("");
        senha_usuario_jpf.setText("");
        data_acesso_usuario_jtf.setText("");
        data_atualizacao_usuario_jtf.setText("");
        tipo_usuario_jcb.setSelectedItem("adm");
        ativo_usuario_rb.setSelected(false);
        revogado_usuario_rb.setSelected(true);
        senhaDesbloqueada_rb.setSelected(false);
        senhaBloqueada_usuario_rb.setSelected(true);         
    }
    
    private void limparTelaTpAgendamento(){
        descricao_tpAgendamento_jtf.setText("");
        tempo_medio_tpAgendamento_jftf.setText("");
        margem_segurança_jftf.setText("");
        hora_inicio_sug_jftf.setText("");
        hora_fim_sug_jftf.setText("");
        justificativa_tpAgendamento_jtf.setText("");
        grupo_tpAgendamento.setText(""); 
        setCod_tpAgendamento(0);
        setCod_grupo(0);        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ativo_usuario_rb;
    private javax.swing.JButton buscarGrupo_tpAgendamento_bt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancelar_grupo_bt;
    private javax.swing.JButton cancelar_tpAgendamento;
    private javax.swing.JButton cancelar_usuario_bt;
    private javax.swing.JFormattedTextField cod_grupo_jftf;
    private javax.swing.JTextField cod_usuario_jtf;
    private javax.swing.JFormattedTextField cor_B_grupo_jftf;
    private javax.swing.JFormattedTextField cor_G_grupo_jftf;
    private javax.swing.JFormattedTextField cor_R_grupo_jftf;
    private javax.swing.JTextField data_acesso_usuario_jtf;
    private javax.swing.JTextField data_atualizacao_usuario_jtf;
    private javax.swing.JTextField descricao_grupo_jtf;
    private javax.swing.JTextField descricao_tpAgendamento_jtf;
    private javax.swing.JButton excluir_grupo_bt;
    private javax.swing.JButton excluir_tpAgendamento;
    private javax.swing.JButton excluir_usuario_bt;
    private javax.swing.JTextField grupo_tpAgendamento;
    private javax.swing.JFormattedTextField hora_fim_sug_jftf;
    private javax.swing.JFormattedTextField hora_inicio_sug_jftf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField justificativa_tpAgendamento_jtf;
    private javax.swing.JTable lista_grupos_jtb;
    private javax.swing.JTable lista_tpAgendamento_JT;
    private javax.swing.JTable lista_usuarios_jtb;
    private javax.swing.JFormattedTextField margem_segurança_jftf;
    private javax.swing.JTextField nome_usuario_jtf;
    private javax.swing.JRadioButton revogado_usuario_rb;
    private javax.swing.JButton salvar_grupo_bt;
    private javax.swing.JButton salvar_tpAgendamento;
    private javax.swing.JButton salvar_usuario_bt;
    private javax.swing.JRadioButton senhaBloqueada_usuario_rb;
    private javax.swing.JRadioButton senhaDesbloqueada_rb;
    private javax.swing.JPasswordField senha_usuario_jpf;
    private javax.swing.JFormattedTextField tempo_medio_tpAgendamento_jftf;
    private javax.swing.JComboBox<String> tipo_usuario_jcb;
    // End of variables declaration//GEN-END:variables

    public int getCod_tpAgendamento() {
        return cod_tpAgendamento;
    }

    public void setCod_tpAgendamento(int cod_tpAgendamento) {
        this.cod_tpAgendamento = cod_tpAgendamento;
    }

    public int getCod_grupo() {
        return cod_grupo;
    }

    public void setCod_grupo(int cod_grupo) {
        this.cod_grupo = cod_grupo;
    }

       

}


